name: 'one_big_table'
version: '1.0.0'
config-version: 2

profile: 'one_big_table'

model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  one_big_table:
    +materialized: table
