name: 'data_vault_20'
version: '1.0.0'
config-version: 2

profile: 'data_vault_20'

model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  data_vault_20:
    staging:
      +materialized: view
    raw_vault:
      hubs:
        +materialized: table
      links:
        +materialized: table
      satellites:
        +materialized: table
    business_vault:
      +materialized: view
